<?php

namespace Database\Seeders;

use App\Models\ManualArticle;
use App\Models\ManualCategory;
use Illuminate\Database\Seeder;

class ManualContentSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            ['name' => 'Inicio y acceso', 'slug' => 'inicio-acceso', 'description' => 'Ingreso, perfil y uso seguro de la cuenta.', 'sort_order' => 10],
            ['name' => 'Solicitudes quirúrgicas', 'slug' => 'solicitudes-quirurgicas', 'description' => 'Registro y seguimiento de cada cirugía.', 'sort_order' => 20],
            ['name' => 'Agenda y recursos', 'slug' => 'agenda-recursos', 'description' => 'Agenda, instrumentistas y cruces operativos.', 'sort_order' => 30],
            ['name' => 'Reservas', 'slug' => 'reservas', 'description' => 'Disponibilidad y reserva por lote.', 'sort_order' => 40],
            ['name' => 'Inventario', 'slug' => 'inventario', 'description' => 'Consulta, estados y control de lotes.', 'sort_order' => 50],
            ['name' => 'Cobertura y forecast', 'slug' => 'cobertura-forecast', 'description' => 'Riesgo de ruptura y reposición MR8.', 'sort_order' => 60],
            ['name' => 'Trazabilidad y escaneo', 'slug' => 'trazabilidad-escaneo', 'description' => 'Identificación por lote, serie y caso.', 'sort_order' => 70],
            ['name' => 'Cierre de cirugía', 'slug' => 'cierre-cirugia', 'description' => 'Consumo, diferencias y valorización inicial.', 'sort_order' => 80],
            ['name' => 'Devoluciones', 'slug' => 'devoluciones', 'description' => 'Retorno e inspección postoperatoria.', 'sort_order' => 90],
            ['name' => 'Fallas técnicas', 'slug' => 'fallas-tecnicas', 'description' => 'Reporte, bloqueo, revisión y liberación.', 'sort_order' => 100],
            ['name' => 'Documentos y evidencias', 'slug' => 'documentos-evidencias', 'description' => 'Carga, validación y trazabilidad documental.', 'sort_order' => 110],
            ['name' => 'Facturación y cobranza', 'slug' => 'facturacion-cobranza', 'description' => 'Valorización, OC, factura y pagos.', 'sort_order' => 120],
            ['name' => 'Reportes', 'slug' => 'reportes', 'description' => 'Lectura de reportes operativos y ejecutivos.', 'sort_order' => 130],
            ['name' => 'Maestros operativos', 'slug' => 'maestros-operativos', 'description' => 'Instituciones, médicos y precios.', 'sort_order' => 140],
            ['name' => 'Usuarios y permisos', 'slug' => 'usuarios-permisos', 'description' => 'Administración de accesos.', 'sort_order' => 150],
            ['name' => 'Seguridad y buenas prácticas', 'slug' => 'seguridad-buenas-practicas', 'description' => 'Reglas transversales para operar con seguridad.', 'sort_order' => 160],
        ];

        foreach ($categories as $categoryData) {
            $category = ManualCategory::query()->firstOrNew(['slug' => $categoryData['slug']]);
            $category->fill($categoryData);
            $category->active = true;
            $category->save();
        }

        $articles = [
            ['category' => 'inicio-acceso', 'slug' => 'iniciar-sesion', 'title' => 'Iniciar sesión y cerrar sesión', 'summary' => 'Accede a OPS BIOMED y termina la sesión de forma segura.', 'level' => 'basico', 'minutes' => 2, 'module' => 'Acceso', 'permission' => null, 'route' => 'profile.edit', 'keywords' => ['login', 'acceso', 'contraseña'], 'steps' => ['Abrir la pantalla de acceso.', 'Ingresar correo y contraseña.', 'Seleccionar Ingresar.', 'Usar Salir en la barra superior al terminar.'], 'fields' => ['Correo electrónico', 'Contraseña'], 'expected' => 'El sistema abre el dashboard permitido para tu rol.', 'errors' => ['Cuenta inactiva o contraseña incorrecta.'], 'blocked' => 'Escala el acceso al Administrador.', 'role' => 'Administrador'],
            ['category' => 'inicio-acceso', 'slug' => 'recuperar-contrasena', 'title' => 'Recuperar contraseña', 'summary' => 'Solicita un enlace de recuperación sin compartir tu contraseña.', 'level' => 'basico', 'minutes' => 2, 'module' => 'Acceso', 'permission' => null, 'route' => 'password.request', 'keywords' => ['password', 'recuperación', 'correo'], 'steps' => ['Abrir ¿Olvidaste tu contraseña?', 'Ingresar el correo registrado.', 'Enviar el enlace.', 'Definir una nueva contraseña desde el enlace temporal.'], 'fields' => ['Correo electrónico'], 'expected' => 'Recibes un enlace temporal para definir una nueva contraseña.', 'errors' => ['El enlace expiró.', 'El correo no está registrado.'], 'blocked' => 'Solicita al Administrador verificar el estado de la cuenta.', 'role' => 'Administrador'],
            ['category' => 'inicio-acceso', 'slug' => 'interpretar-el-dashboard', 'title' => 'Interpretar el dashboard', 'summary' => 'Lee las prioridades de la Torre de Control en pocos segundos.', 'level' => 'basico', 'minutes' => 4, 'module' => 'Dashboard', 'permission' => 'dashboard.view', 'route' => 'dashboard.ops', 'keywords' => ['dashboard', 'alertas', 'kpi'], 'steps' => ['Revisar la banda crítica superior.', 'Abrir la agenda quirúrgica.', 'Revisar Inventario MR8 y Finanzas.', 'Entrar al detalle de la prioridad.'], 'fields' => [], 'expected' => 'Identificas qué cirugía, material o cobranza requiere acción.', 'errors' => ['Confundir un indicador informativo con una alerta crítica.'], 'blocked' => 'Verifica el permiso de tu rol.', 'role' => 'Jefe de Linea'],
            ['category' => 'solicitudes-quirurgicas', 'slug' => 'consultar-solicitudes', 'title' => 'Consultar solicitudes', 'summary' => 'Busca una cirugía, revisa su estado y abre el control operativo.', 'level' => 'basico', 'minutes' => 3, 'module' => 'Solicitudes', 'permission' => 'cases.view', 'route' => 'cases.index', 'keywords' => ['solicitud', 'caso', 'cirugía', 'estado'], 'steps' => ['Abrir Solicitudes.', 'Filtrar por estado o fecha.', 'Seleccionar el código interno.', 'Revisar estado y control operativo.'], 'fields' => [], 'expected' => 'Encuentras el caso y confirmas su siguiente acción.', 'errors' => ['Buscar por nombre completo cuando corresponde usar el código interno.'], 'blocked' => 'Pide el código al Programador Quirúrgico.', 'role' => 'Programador Quirurgico'],
            ['category' => 'solicitudes-quirurgicas', 'slug' => 'crear-solicitud-quirurgica', 'title' => 'Crear una solicitud quirúrgica', 'summary' => 'Registra una cirugía con los datos mínimos para iniciar la operación.', 'level' => 'operativo', 'minutes' => 3, 'module' => 'Solicitudes', 'permission' => 'cases.create', 'route' => 'cases.create', 'keywords' => ['crear', 'institución', 'médico', 'paciente', 'material'], 'steps' => ['Abrir Nueva solicitud.', 'Seleccionar institución y médico activos.', 'Registrar paciente y tipo de cirugía.', 'Completar fecha, hora, origen y material.', 'Guardar y verificar solicitud_registrada.'], 'fields' => ['Institución', 'Médico', 'Paciente', 'Tipo de cirugía', 'Fecha y hora', 'Origen', 'Material solicitado'], 'expected' => 'El caso queda creado con código interno y estado solicitud_registrada.', 'errors' => ['Institución o médico inactivo.', 'Fecha y hora vacías.'], 'blocked' => 'Completa los obligatorios antes de continuar a reserva.', 'role' => 'Programador Quirurgico'],
            ['category' => 'solicitudes-quirurgicas', 'slug' => 'control-operativo-de-una-cirugia', 'title' => 'Control operativo de una cirugía', 'summary' => 'Revisa estado, material, evidencias y pendientes desde una vista única.', 'level' => 'operativo', 'minutes' => 4, 'module' => 'Solicitudes', 'permission' => 'cases.view', 'route' => 'cases.index', 'keywords' => ['control', 'línea de tiempo', 'alertas', 'caso'], 'steps' => ['Abrir el detalle del caso.', 'Seleccionar Control operativo.', 'Revisar la línea de tiempo.', 'Atender alertas antes de avanzar.', 'Usar acciones según tu permiso.'], 'fields' => [], 'expected' => 'Tienes una lectura completa del estado y pendientes del caso.', 'errors' => ['Intentar avanzar sin resolver bloqueos.'], 'blocked' => 'Revisa la alerta y escala al responsable.', 'role' => 'Jefe de Linea'],
            ['category' => 'agenda-recursos', 'slug' => 'revisar-agenda-y-conflictos', 'title' => 'Revisar agenda y conflictos', 'summary' => 'Detecta cruces de instrumentistas, recursos y cirugías próximas.', 'level' => 'supervision', 'minutes' => 4, 'module' => 'Agenda', 'permission' => 'schedule.view', 'route' => 'schedule.index', 'keywords' => ['agenda', 'conflictos', 'instrumentista', 'recurso'], 'steps' => ['Abrir Agenda quirúrgica.', 'Cambiar entre día, semana y 48 horas.', 'Abrir Conflictos.', 'Revisar severidad y acción sugerida.', 'Resolver o escalar el cruce.'], 'fields' => [], 'expected' => 'La agenda queda sin cruces críticos conocidos.', 'errors' => ['Asignar un mismo recurso a horarios simultáneos.'], 'blocked' => 'No prometas la atención hasta corregir un conflicto crítico.', 'role' => 'Jefe de Linea'],
            ['category' => 'reservas', 'slug' => 'reservar-material-por-lote', 'title' => 'Reservar material por lote', 'summary' => 'Reserva material elegible para una cirugía y valida el disponible neto.', 'level' => 'operativo', 'minutes' => 5, 'module' => 'Reservas', 'permission' => 'reservations.create', 'route' => 'cases.index', 'keywords' => ['reserva', 'lote', 'disponibilidad', 'YSAN'], 'steps' => ['Abrir el caso.', 'Seleccionar Reservar material.', 'Revisar semáforo y disponible neto.', 'Elegir lote o ingresar su código trazable.', 'Indicar cantidad positiva y confirmar.'], 'fields' => ['Lote', 'Cantidad'], 'expected' => 'La reserva queda vinculada al caso y el stock neto se actualiza.', 'errors' => ['Cantidad mayor al disponible.', 'Lote vencido, bloqueado o desvalorizado.'], 'blocked' => 'Selecciona otro lote o escala la falta de stock.', 'role' => 'Almacen'],
            ['category' => 'inventario', 'slug' => 'buscar-inventario', 'title' => 'Buscar inventario', 'summary' => 'Consulta producto, lote, serie, ubicación y elegibilidad.', 'level' => 'basico', 'minutes' => 4, 'module' => 'Inventario', 'permission' => 'inventory.view', 'route' => 'inventory.index', 'keywords' => ['inventario', 'lote', 'serie', 'vencimiento', 'almacén'], 'steps' => ['Abrir Inventario.', 'Filtrar por producto, lote, almacén o estado.', 'Abrir el detalle del lote.', 'Revisar disponible neto, reservas y alertas.', 'Usar la etiqueta para identificarlo.'], 'fields' => [], 'expected' => 'Confirmas si el lote puede reservarse y dónde se encuentra.', 'errors' => ['Confundir stock total con elegible inmediato.'], 'blocked' => 'No retires un lote con alerta; consulta a Almacén o Dirección Técnica.', 'role' => 'Almacen'],
            ['category' => 'cobertura-forecast', 'slug' => 'analizar-cobertura-y-forecast', 'title' => 'Analizar cobertura y forecast', 'summary' => 'Interpreta el semáforo MR8 y la recomendación de reposición.', 'level' => 'supervision', 'minutes' => 5, 'module' => 'Cobertura MR8', 'permission' => 'inventory.view', 'route' => 'inventory.coverage', 'keywords' => ['cobertura', 'forecast', 'mínimo', 'objetivo', 'compra'], 'steps' => ['Abrir Cobertura MR8.', 'Revisar combinaciones rojas y amarillas.', 'Confirmar YSAN como respaldo separado.', 'Abrir Forecast MR8.', 'Exportar y escalar compras según urgencia.'], 'fields' => [], 'expected' => 'Identificas faltantes reales sin contar material no elegible.', 'errors' => ['Contar YSAN como inmediato.', 'Ignorar reservas activas.'], 'blocked' => 'Revisa equivalencia o inconsistencia antes de comprar.', 'role' => 'Jefe de Linea'],
            ['category' => 'trazabilidad-escaneo', 'slug' => 'escanear-codigo-trazable', 'title' => 'Escanear un código trazable', 'summary' => 'Identifica lotes, casos y reservas con lector físico o código escrito.', 'level' => 'operativo', 'minutes' => 3, 'module' => 'Trazabilidad', 'permission' => 'trace.scan', 'route' => 'trace.index', 'keywords' => ['QR', 'código', 'barcode', 'lote', 'escaneo'], 'steps' => ['Abrir Escanear.', 'Enfocar el campo.', 'Leer o escribir el código.', 'Presionar Enter.', 'Revisar estado, ubicación y acciones disponibles.'], 'fields' => ['Código trazable'], 'expected' => 'El sistema identifica el registro y registra el escaneo.', 'errors' => ['Código inexistente o ilegible.'], 'blocked' => 'Verifica la etiqueta y no cambies stock por un escaneo fallido.', 'role' => 'Almacen'],
            ['category' => 'cierre-cirugia', 'slug' => 'cerrar-una-cirugia', 'title' => 'Cerrar una cirugía', 'summary' => 'Registra consumo, devoluciones, material abierto, fallas y evidencia.', 'level' => 'operativo', 'minutes' => 7, 'module' => 'Cierre quirúrgico', 'permission' => 'cases.close', 'route' => 'cases.index', 'keywords' => ['cierre', 'consumo', 'usado', 'devuelto', 'evidencia'], 'steps' => ['Abrir el caso y seleccionar Cerrar cirugía.', 'Completar cantidades por lote.', 'Registrar diferencias con motivo.', 'Describir toda falla.', 'Adjuntar evidencia y guardar.'], 'fields' => ['Usada', 'Abierta no usada', 'Devuelta', 'Falla', 'Evidencia'], 'expected' => 'El caso pasa a cerrado y queda listo para conciliación.', 'errors' => ['Cantidades que no concilian.', 'Evidencia ausente.'], 'blocked' => 'No fuerces el cierre; completa el motivo o escala la diferencia.', 'role' => 'Instrumentista'],
            ['category' => 'fallas-tecnicas', 'slug' => 'reportar-falla-tecnica', 'title' => 'Reportar una falla técnica', 'summary' => 'Registra una falla y activa el bloqueo preventivo correspondiente.', 'level' => 'operativo', 'minutes' => 4, 'module' => 'Fallas técnicas', 'permission' => 'failures.create', 'route' => 'failures.create', 'keywords' => ['falla', 'bloqueo', 'mantenimiento'], 'steps' => ['Abrir Fallas técnicas.', 'Seleccionar producto y lote.', 'Indicar tipo, momento y severidad.', 'Registrar descripción y acción inmediata.', 'Adjuntar evidencia y guardar.'], 'fields' => ['Tipo', 'Momento', 'Severidad', 'Descripción'], 'expected' => 'La falla queda reportada y el lote se bloquea según la regla.', 'errors' => ['Omitir lote o evidencia.'], 'blocked' => 'No reserves ni liberes el lote hasta la revisión autorizada.', 'role' => 'Direccion Tecnica'],
            ['category' => 'devoluciones', 'slug' => 'inspeccionar-devolucion', 'title' => 'Inspeccionar una devolución', 'summary' => 'Decide si el material retornado vuelve a disponible, queda en cuarentena o se retira.', 'level' => 'supervision', 'minutes' => 5, 'module' => 'Devoluciones', 'permission' => 'returns.view', 'route' => 'returns.index', 'keywords' => ['devolución', 'inspección', 'cuarentena'], 'steps' => ['Abrir Devoluciones.', 'Filtrar pendientes de inspección.', 'Revisar caso, lote, evidencia y fallas.', 'Registrar resultado y observaciones.', 'Confirmar el estado final.'], 'fields' => ['Resultado', 'Observaciones', 'Responsable'], 'expected' => 'La devolución queda liberada, en cuarentena, bloqueada o retirada.', 'errors' => ['Liberar material vencido o con falla abierta.'], 'blocked' => 'Mantén el lote en cuarentena y escala a Dirección Técnica.', 'role' => 'Direccion Tecnica'],
            ['category' => 'documentos-evidencias', 'slug' => 'adjuntar-documentos-y-evidencias', 'title' => 'Adjuntar documentos y evidencias', 'summary' => 'Centraliza enlaces y archivos de solicitudes, consumo, fallas y devoluciones.', 'level' => 'operativo', 'minutes' => 3, 'module' => 'Documentos', 'permission' => 'documents.view', 'route' => 'documents.index', 'keywords' => ['documento', 'evidencia', 'archivo', 'link'], 'steps' => ['Abrir Documentos o el caso.', 'Seleccionar tipo documental.', 'Cargar archivo o enlace.', 'Completar título y fecha.', 'Guardar y solicitar validación.'], 'fields' => ['Tipo', 'Título', 'Archivo o enlace'], 'expected' => 'La evidencia queda relacionada y trazable.', 'errors' => ['Tipo de archivo no permitido.', 'Documento sin relación.'], 'blocked' => 'No envíes datos sensibles a servicios externos; consulta a Cumplimiento.', 'role' => 'Jefe de Linea'],
            ['category' => 'facturacion-cobranza', 'slug' => 'revisar-facturacion-y-cobranza', 'title' => 'Revisar facturación y cobranza', 'summary' => 'Controla valorización, OC, factura, pagos y deuda por cirugía.', 'level' => 'supervision', 'minutes' => 5, 'module' => 'Facturación', 'permission' => 'billing.view', 'route' => 'billing.index', 'keywords' => ['factura', 'OC', 'pago', 'deuda'], 'steps' => ['Abrir Facturación / Cobranza.', 'Filtrar por estado.', 'Revisar valorización y OC.', 'Completar factura con número válido.', 'Registrar pagos y confirmar saldo.'], 'fields' => ['Estado', 'Número de factura', 'Monto pagado'], 'expected' => 'El estado administrativo refleja la situación real.', 'errors' => ['Marcar pagado con saldo.', 'Facturar sin número.'], 'blocked' => 'Corrige la conciliación o escala a Cobranza.', 'role' => 'Cobranza'],
            ['category' => 'reportes', 'slug' => 'consultar-reportes-ejecutivos', 'title' => 'Consultar reportes ejecutivos', 'summary' => 'Usa filtros y exportaciones para el seguimiento de la operación.', 'level' => 'supervision', 'minutes' => 4, 'module' => 'Reportes', 'permission' => 'reports.view', 'route' => 'reports.index', 'keywords' => ['reportes', 'operativo', 'comercial', 'inventario'], 'steps' => ['Abrir Reportes.', 'Elegir el área.', 'Aplicar rango y filtros.', 'Leer indicadores y detalle.', 'Exportar CSV si corresponde.'], 'fields' => [], 'expected' => 'Obtienes una lectura reproducible del periodo.', 'errors' => ['Comparar periodos distintos.', 'Compartir información no autorizada.'], 'blocked' => 'Solicita el permiso de reportes apropiado.', 'role' => 'Gerencia'],
            ['category' => 'maestros-operativos', 'slug' => 'administrar-maestros-operativos', 'title' => 'Administrar instituciones, médicos y precios', 'summary' => 'Mantén los maestros que alimentan solicitudes y valorización.', 'level' => 'administracion', 'minutes' => 6, 'module' => 'Maestros', 'permission' => 'masters.view', 'route' => 'masters.institutions.index', 'keywords' => ['institución', 'médico', 'precio', 'maestros'], 'steps' => ['Abrir Maestros.', 'Crear o buscar el registro.', 'Validar identificadores únicos.', 'Completar estado y condición.', 'Guardar y verificar el uso en nuevas solicitudes.'], 'fields' => ['Nombre', 'RUC o CMP cuando aplique', 'Producto y precio'], 'expected' => 'Las nuevas solicitudes y valorizaciones usan datos vigentes.', 'errors' => ['Duplicar RUC o CMP.'], 'blocked' => 'Escala la modificación al Administrador o Jefe de Línea.', 'role' => 'Administrador'],
            ['category' => 'usuarios-permisos', 'slug' => 'administrar-usuarios-y-permisos', 'title' => 'Administrar usuarios y permisos', 'summary' => 'Crea usuarios, asigna roles y conserva el control de acceso.', 'level' => 'administracion', 'minutes' => 5, 'module' => 'Administración', 'permission' => 'users.manage', 'route' => 'admin.users.index', 'keywords' => ['usuarios', 'roles', 'permisos'], 'steps' => ['Abrir Administración / Usuarios.', 'Crear el usuario con correo único.', 'Asignar el rol.', 'Entregar la contraseña temporal por canal seguro.', 'Activar o desactivar según corresponda.'], 'fields' => ['Nombre', 'Correo', 'Rol', 'Contraseña temporal'], 'expected' => 'El usuario accede únicamente a los módulos de su rol.', 'errors' => ['Quitar al último Administrador.', 'Desactivar la propia cuenta.'], 'blocked' => 'Solicita al Administrador corregir el acceso.', 'role' => 'Administrador'],
            ['category' => 'seguridad-buenas-practicas', 'slug' => 'seguridad-y-buenas-practicas', 'title' => 'Seguridad y buenas prácticas operativas', 'summary' => 'Protege pacientes, inventario y trazabilidad durante la operación.', 'level' => 'basico', 'minutes' => 5, 'module' => 'Seguridad', 'permission' => null, 'route' => 'compliance.ai-policy', 'keywords' => ['seguridad', 'datos', 'auditoría', 'IA'], 'steps' => ['Usar tu propia cuenta.', 'Registrar la operación en el módulo correcto.', 'No compartir datos sensibles innecesarios.', 'Verificar lote, vencimiento y estado.', 'Adjuntar evidencia y escalar bloqueos.'], 'fields' => [], 'expected' => 'La operación queda segura, trazable y auditable.', 'errors' => ['Cuentas compartidas.', 'Omitir fallas o diferencias.'], 'blocked' => 'Detén la operación y escala al responsable.', 'role' => 'Jefe de Linea'],
            ['category' => 'cobertura-forecast', 'slug' => 'resolver-alertas-operativas', 'title' => 'Resolver alertas operativas', 'summary' => 'Prioriza alertas SLA y documenta la acción humana tomada.', 'level' => 'supervision', 'minutes' => 4, 'module' => 'Alertas', 'permission' => 'dashboard.view', 'route' => 'dashboard.ops', 'keywords' => ['alerta', 'SLA', 'prioridad'], 'steps' => ['Abrir el detalle de la alerta.', 'Verificar el caso y la fuente.', 'Identificar al responsable.', 'Ejecutar la acción en el módulo transaccional.', 'Registrar evidencia y confirmar actualización.'], 'fields' => ['Acción tomada', 'Responsable'], 'expected' => 'La alerta queda atendida o escalada con trazabilidad.', 'errors' => ['Cerrar una alerta sin resolver su causa.'], 'blocked' => 'Escala la alerta manteniéndola visible.', 'role' => 'Jefe de Linea'],
            ['category' => 'inicio-acceso', 'slug' => 'actualizar-perfil', 'title' => 'Actualizar el perfil', 'summary' => 'Mantén tus datos de contacto y contraseña actualizados sin cambiar tu rol.', 'level' => 'basico', 'minutes' => 3, 'module' => 'Perfil', 'permission' => null, 'route' => 'profile.edit', 'keywords' => ['perfil', 'contraseña', 'correo', 'seguridad'], 'steps' => ['Abrir tu nombre en la barra superior.', 'Actualizar nombre, correo o datos disponibles.', 'Guardar los cambios.', 'Usar el formulario de contraseña cuando corresponda.'], 'fields' => ['Nombre', 'Correo electrónico', 'Contraseña actual'], 'expected' => 'Tus datos personales quedan actualizados y tu rol permanece controlado por Administración.', 'errors' => ['Intentar cambiar el rol desde el perfil.'], 'blocked' => 'Solicita cualquier cambio de rol al Administrador.', 'role' => 'Todos los roles'],
            ['category' => 'solicitudes-quirurgicas', 'slug' => 'editar-solicitud-segun-estado', 'title' => 'Editar una solicitud según su estado', 'summary' => 'Actualiza una solicitud sin alterar su código interno ni saltarte controles.', 'level' => 'operativo', 'minutes' => 4, 'module' => 'Solicitudes', 'permission' => 'cases.view', 'route' => 'cases.index', 'keywords' => ['editar', 'estado', 'programada', 'reservada'], 'steps' => ['Abrir la solicitud.', 'Seleccionar Editar cuando el estado lo permita.', 'Modificar solo los campos habilitados.', 'Revisar la fecha, material y observaciones.', 'Guardar y confirmar el mensaje de éxito.'], 'fields' => ['Campos obligatorios según estado', 'Motivo u observación cuando aplique'], 'expected' => 'La solicitud se actualiza manteniendo trazabilidad y restricciones por estado.', 'errors' => ['Intentar editar una solicitud cerrada o facturada.'], 'blocked' => 'Escala el cambio al Jefe de Línea si el estado bloquea la edición.', 'role' => 'Programador Quirurgico'],
            ['category' => 'agenda-recursos', 'slug' => 'consultar-agenda', 'title' => 'Consultar la agenda quirúrgica', 'summary' => 'Visualiza cirugías próximas y detecta cruces antes de la atención.', 'level' => 'basico', 'minutes' => 3, 'module' => 'Agenda', 'permission' => 'schedule.view', 'route' => 'schedule.index', 'keywords' => ['agenda', 'cirugía', 'día', 'semana', '48 horas'], 'steps' => ['Abrir Agenda quirúrgica.', 'Elegir vista de día, semana o próximas 48 horas.', 'Revisar hora, institución, médico y estado.', 'Abrir el control operativo del caso cuando necesites más detalle.'], 'fields' => [], 'expected' => 'Conoces la carga quirúrgica próxima y sus alertas visibles.', 'errors' => ['Confundir una cirugía informativa con una reserva completa.'], 'blocked' => 'Solicita acceso a Agenda al Administrador.', 'role' => 'Todos los roles operativos'],
            ['category' => 'agenda-recursos', 'slug' => 'asignar-instrumentistas-y-recursos', 'title' => 'Asignar instrumentistas y recursos', 'summary' => 'Asigna responsables y recursos reutilizables evitando cruces de horario.', 'level' => 'supervision', 'minutes' => 5, 'module' => 'Agenda', 'permission' => 'schedule.manage', 'route' => 'schedule.index', 'keywords' => ['instrumentista', 'recurso', 'motor', 'consola', 'conflicto'], 'steps' => ['Abrir la agenda del caso.', 'Seleccionar el instrumentista disponible.', 'Asignar equipos o sets cuando existan.', 'Revisar conflictos antes de guardar.', 'Confirmar la asignación en el control operativo.'], 'fields' => ['Instrumentista', 'Recurso reutilizable', 'Observación'], 'expected' => 'El caso cuenta con responsable y recursos sin cruces conocidos.', 'errors' => ['Asignar el mismo recurso a dos cirugías simultáneas.'], 'blocked' => 'Corrige el conflicto antes de prometer la atención.', 'role' => 'Jefe de Linea'],
            ['category' => 'cobertura-forecast', 'slug' => 'validar-cobertura-mr8', 'title' => 'Validar cobertura MR8', 'summary' => 'Confirma si el kit requerido cubre tres cirugías y alcanza el objetivo de cinco.', 'level' => 'operativo', 'minutes' => 4, 'module' => 'Cobertura MR8', 'permission' => 'inventory.view', 'route' => 'inventory.coverage', 'keywords' => ['cobertura', 'mínimo', 'objetivo', 'semáforo', 'kit'], 'steps' => ['Abrir Cobertura MR8.', 'Seleccionar el tipo de cirugía.', 'Revisar combinaciones rojas y amarillas.', 'Confirmar que YSAN no cuenta como inmediato.', 'Abrir forecast si se necesita reposición.'], 'fields' => [], 'expected' => 'La cobertura refleja solo stock elegible neto y reservas activas.', 'errors' => ['Contar lotes vencidos, bloqueados o desvalorizados.'], 'blocked' => 'Escala el faltante a Jefe de Línea o Comercial antes de comprometer una fecha.', 'role' => 'Jefe de Linea'],
            ['category' => 'inventario', 'slug' => 'revisar-inconsistencias-de-inventario', 'title' => 'Revisar inconsistencias de inventario', 'summary' => 'Identifica cantidades negativas y advertencias sin convertirlas en stock disponible.', 'level' => 'supervision', 'minutes' => 4, 'module' => 'Inventario', 'permission' => 'inventory.view', 'route' => 'inventory.index', 'keywords' => ['inconsistencia', 'negativo', 'importación', 'stock'], 'steps' => ['Abrir Inventario MR8.', 'Localizar la alerta del lote o importación.', 'Comparar cantidad física y sistema.', 'Mantener cantidades negativas fuera del stock elegible.', 'Registrar o escalar el ajuste correspondiente.'], 'fields' => ['Producto', 'Lote', 'Almacén', 'Observación'], 'expected' => 'La inconsistencia queda visible y no distorsiona la disponibilidad inmediata.', 'errors' => ['Usar una cantidad negativa como stock reservado.'], 'blocked' => 'Escala la diferencia a Almacén y Jefe de Línea.', 'role' => 'Almacen'],
            ['category' => 'fallas-tecnicas', 'slug' => 'revisar-fallas-tecnicas', 'title' => 'Revisar fallas técnicas', 'summary' => 'Da seguimiento a bloqueos, diagnósticos, liberaciones y bajas de material.', 'level' => 'supervision', 'minutes' => 5, 'module' => 'Fallas técnicas', 'permission' => 'failures.view', 'route' => 'failures.index', 'keywords' => ['falla', 'bloqueo', 'diagnóstico', 'liberación', 'baja'], 'steps' => ['Abrir Fallas técnicas.', 'Filtrar por estado y severidad.', 'Revisar producto, lote, caso y evidencia.', 'Registrar seguimiento técnico cuando corresponda.', 'Liberar o retirar solo con autorización.'], 'fields' => ['Estado', 'Diagnóstico', 'Acción correctiva', 'Evidencia'], 'expected' => 'Cada falla mantiene un estado técnico claro y el lote conserva el bloqueo preventivo cuando corresponde.', 'errors' => ['Liberar un lote vencido o con otra falla abierta.'], 'blocked' => 'Mantén el lote bloqueado y escala a Dirección Técnica.', 'role' => 'Direccion Tecnica'],
            ['category' => 'facturacion-cobranza', 'slug' => 'aprobar-costos-cero', 'title' => 'Aprobar costos cero', 'summary' => 'Revisa el sustento y aprueba o rechaza costos cero sin omitir la trazabilidad.', 'level' => 'supervision', 'minutes' => 4, 'module' => 'Aprobaciones', 'permission' => 'approvals.approve', 'route' => 'approvals.cost-zero.index', 'keywords' => ['costo cero', 'aprobación', 'sustento', 'valorización'], 'steps' => ['Abrir Aprobaciones.', 'Revisar caso, institución, producto y motivo.', 'Validar que exista sustento.', 'Aprobar o rechazar la solicitud.', 'Confirmar el estado de facturación resultante.'], 'fields' => ['Motivo de costo cero', 'Decisión', 'Observación'], 'expected' => 'La solicitud queda aprobada o rechazada con usuario y fecha auditables.', 'errors' => ['Aprobar sin motivo o con datos incompletos.'], 'blocked' => 'Devuelve la solicitud para corrección y no la marques como aprobada.', 'role' => 'Gerencia'],
            ['category' => 'facturacion-cobranza', 'slug' => 'revisar-conciliaciones', 'title' => 'Revisar conciliaciones', 'summary' => 'Comprueba que reservado, usado, devuelto y fallado estén conciliados antes de cobrar.', 'level' => 'supervision', 'minutes' => 5, 'module' => 'Facturación', 'permission' => 'billing.view', 'route' => 'billing.index', 'keywords' => ['conciliación', 'consumo', 'diferencia', 'cobranza'], 'steps' => ['Abrir el caso o Facturación / Cobranza.', 'Comparar cantidades por lote.', 'Leer motivos de diferencia.', 'Confirmar que el caso tenga evidencia.', 'Escalar faltantes antes de facturar.'], 'fields' => ['Motivo de diferencia', 'Evidencia', 'Estado de conciliación'], 'expected' => 'El caso queda conciliado o observado antes de avanzar administrativamente.', 'errors' => ['Facturar una diferencia sin justificar.'], 'blocked' => 'Devuelve el caso a Operación para completar la conciliación.', 'role' => 'Cobranza'],
        ];

        foreach ($articles as $index => $articleData) {
            $categoryId = ManualCategory::query()->where('slug', $articleData['category'])->value('id');
            $article = ManualArticle::query()->firstOrNew(['slug' => $articleData['slug']]);
            $article->fill([
                'category_id' => $categoryId,
                'title' => $articleData['title'],
                'summary' => $articleData['summary'],
                'level' => $articleData['level'],
                'body' => $articleData['summary'],
                'estimated_minutes' => $articleData['minutes'],
                'roles_json' => [],
                'keywords_json' => $articleData['keywords'],
                'prerequisites_json' => [],
                'steps_json' => $articleData['steps'],
                'required_fields_json' => $articleData['fields'],
                'expected_result' => $articleData['expected'],
                'common_errors_json' => $articleData['errors'],
                'blocked_action' => $articleData['blocked'],
                'escalation_role' => $articleData['role'],
                'module' => $articleData['module'],
                'permission' => $articleData['permission'],
                'route_name' => $articleData['route'],
                'sort_order' => $articleData['sort_order'] ?? ($index + 1),
                'active' => true,
                'version' => '1.0',
                'published_at' => now(),
            ]);
            $article->save();
        }
    }
}
