@php
    $editing = isset($doctor);
    $specialtyLabels = ['neurocirugia' => 'Neurocirugia', 'columna' => 'Columna', 'otorrino' => 'Otorrino', 'cabeza_cuello' => 'Cabeza y cuello', 'traumatologia' => 'Traumatologia', 'otro' => 'Otro'];
    $profileLabels = ['clave' => 'Clave', 'frecuente' => 'Frecuente', 'ocasional' => 'Ocasional', 'nuevo' => 'Nuevo', 'inactivo' => 'Inactivo'];
    $potentialLabels = ['alto' => 'Alto', 'medio' => 'Medio', 'bajo' => 'Bajo'];
@endphp

<div class="grid gap-5 md:grid-cols-2">
    <div class="md:col-span-2"><label for="name" class="block text-sm font-medium text-slate-700">Nombre <span class="text-rose-600">*</span></label><input id="name" name="name" type="text" value="{{ old('name', $doctor->name ?? '') }}" required maxlength="180" class="mt-1.5 block w-full border-slate-300 text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500">@error('name')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div><label for="cmp" class="block text-sm font-medium text-slate-700">CMP</label><input id="cmp" name="cmp" type="text" value="{{ old('cmp', $doctor->cmp ?? '') }}" maxlength="30" class="mt-1.5 block w-full border-slate-300 text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500">@error('cmp')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div><label for="specialty" class="block text-sm font-medium text-slate-700">Especialidad <span class="text-rose-600">*</span></label><select id="specialty" name="specialty" required class="mt-1.5 block w-full border-slate-300 bg-white text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500">@foreach ($specialties as $value)<option value="{{ $value }}" @selected(old('specialty', $doctor->specialty ?? 'otro') === $value)>{{ $specialtyLabels[$value] }}</option>@endforeach</select>@error('specialty')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div><label for="institution_id" class="block text-sm font-medium text-slate-700">Institucion principal</label><select id="institution_id" name="institution_id" class="mt-1.5 block w-full border-slate-300 bg-white text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500"><option value="">Sin institucion principal</option>@foreach ($institutions as $institution)<option value="{{ $institution->id }}" @selected(old('institution_id', $doctor->institution_id ?? '') == $institution->id)>{{ $institution->name }}{{ $institution->active ? '' : ' (inactiva)' }}</option>@endforeach</select>@error('institution_id')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div><label for="commercial_owner_id" class="block text-sm font-medium text-slate-700">Responsable comercial</label><select id="commercial_owner_id" name="commercial_owner_id" class="mt-1.5 block w-full border-slate-300 bg-white text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500"><option value="">Sin asignar</option>@foreach ($commercialOwners as $owner)<option value="{{ $owner->id }}" @selected(old('commercial_owner_id', $doctor->commercial_owner_id ?? '') == $owner->id)>{{ $owner->name }}</option>@endforeach</select>@error('commercial_owner_id')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div><label for="phone" class="block text-sm font-medium text-slate-700">Telefono</label><input id="phone" name="phone" type="text" value="{{ old('phone', $doctor->phone ?? '') }}" maxlength="50" class="mt-1.5 block w-full border-slate-300 text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500">@error('phone')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div><label for="email" class="block text-sm font-medium text-slate-700">Email</label><input id="email" name="email" type="email" value="{{ old('email', $doctor->email ?? '') }}" maxlength="180" class="mt-1.5 block w-full border-slate-300 text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500">@error('email')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div><label for="commercial_profile" class="block text-sm font-medium text-slate-700">Perfil comercial <span class="text-rose-600">*</span></label><select id="commercial_profile" name="commercial_profile" required class="mt-1.5 block w-full border-slate-300 bg-white text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500">@foreach ($commercialProfiles as $value)<option value="{{ $value }}" @selected(old('commercial_profile', $doctor->commercial_profile ?? 'nuevo') === $value)>{{ $profileLabels[$value] }}</option>@endforeach</select>@error('commercial_profile')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div><label for="potential" class="block text-sm font-medium text-slate-700">Potencial <span class="text-rose-600">*</span></label><select id="potential" name="potential" required class="mt-1.5 block w-full border-slate-300 bg-white text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500">@foreach ($potentials as $value)<option value="{{ $value }}" @selected(old('potential', $doctor->potential ?? 'medio') === $value)>{{ $potentialLabels[$value] }}</option>@endforeach</select>@error('potential')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div class="md:col-span-2"><label for="observations" class="block text-sm font-medium text-slate-700">Observaciones</label><textarea id="observations" name="observations" rows="4" maxlength="2000" class="mt-1.5 block w-full border-slate-300 text-sm shadow-sm focus:border-sky-500 focus:ring-sky-500">{{ old('observations', $doctor->observations ?? '') }}</textarea>@error('observations')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div class="md:col-span-2"><label class="inline-flex items-center gap-3 text-sm font-medium text-slate-700"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked(old('active', $doctor->active ?? true)) class="border-slate-300 text-sky-700 focus:ring-sky-500">Medico activo</label>@error('active')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
</div>

<div class="flex flex-col-reverse gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:justify-end"><a href="{{ route('masters.doctors.index') }}" class="inline-flex items-center justify-center border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancelar</a><button type="submit" class="inline-flex items-center justify-center bg-sky-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-sky-800">{{ $editing ? 'Guardar cambios' : 'Crear medico' }}</button></div>
