@extends('layouts.ops')

@section('title', 'Medicos | OPS BIOMED MR8')

@section('content')
    <div class="space-y-6">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-sky-700">Maestros operativos</p><h1 class="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Medicos</h1><p class="mt-2 text-sm text-slate-500">Mantiene perfiles, especialidades y responsables comerciales.</p></div>@can('masters.manage')<a href="{{ route('masters.doctors.create') }}" class="inline-flex items-center justify-center bg-sky-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-sky-800">Nuevo medico</a>@endcan</div>
        <form method="GET" class="grid gap-4 border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><div><label for="active" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Estado</label><select id="active" name="active" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todos</option><option value="active" @selected(request('active') === 'active')>Activos</option><option value="inactive" @selected(request('active') === 'inactive')>Inactivos</option></select></div><div><label for="specialty" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Especialidad</label><select id="specialty" name="specialty" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todas</option>@foreach ($specialties as $value)<option value="{{ $value }}" @selected(request('specialty') === $value)>{{ str_replace('_', ' ', ucfirst($value)) }}</option>@endforeach</select></div><div><label for="commercial_profile" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Perfil comercial</label><select id="commercial_profile" name="commercial_profile" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todos</option>@foreach ($commercialProfiles as $value)<option value="{{ $value }}" @selected(request('commercial_profile') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div><div><label for="potential" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Potencial</label><select id="potential" name="potential" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todos</option>@foreach ($potentials as $value)<option value="{{ $value }}" @selected(request('potential') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div><div class="sm:col-span-2 lg:col-span-4 flex justify-end gap-3"><a href="{{ route('masters.doctors.index') }}" class="border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Limpiar</a><button type="submit" class="bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800">Filtrar</button></div></form>
        <div class="overflow-hidden border border-slate-200 bg-white shadow-sm">@if ($doctors->isEmpty())<div class="px-6 py-12 text-center text-sm text-slate-500">No hay medicos registrados.</div>@else<div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Medico</th><th class="px-5 py-3">CMP</th><th class="px-5 py-3">Especialidad</th><th class="px-5 py-3">Institucion</th><th class="px-5 py-3">Perfil</th><th class="px-5 py-3">Potencial</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($doctors as $doctor)<tr class="align-top"><td class="px-5 py-4"><a href="{{ route('masters.doctors.show', $doctor) }}" class="font-semibold text-sky-700 hover:text-sky-900">{{ $doctor->name }}</a></td><td class="px-5 py-4 text-slate-600">{{ $doctor->cmp ?: '—' }}</td><td class="px-5 py-4 text-slate-600">{{ str_replace('_', ' ', ucfirst($doctor->specialty ?: 'otro')) }}</td><td class="px-5 py-4 text-slate-600">{{ $doctor->institution?->name ?: '—' }}</td><td class="px-5 py-4 text-slate-600">{{ ucfirst($doctor->commercial_profile ?: 'nuevo') }}</td><td class="px-5 py-4 text-slate-600">{{ ucfirst($doctor->potential ?: 'medio') }}</td><td class="px-5 py-4"><span class="inline-flex px-2 py-1 text-xs font-semibold {{ $doctor->active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $doctor->active ? 'Activo' : 'Inactivo' }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('masters.doctors.edit', $doctor) }}" class="font-semibold text-slate-700 hover:text-sky-700">Editar</a></td></tr>@endforeach</tbody></table></div><div class="border-t border-slate-200 px-5 py-4">{{ $doctors->links() }}</div>@endif</div>
    </div>
@endsection
