@extends('layouts.ops')

@section('title', $doctor->name.' | OPS BIOMED MR8')

@section('content')
    <div class="space-y-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{ route('masters.doctors.index') }}" class="text-sm font-medium text-sky-700 hover:text-sky-900">Volver a medicos</a><h1 class="mt-3 text-2xl font-semibold tracking-tight text-slate-950">{{ $doctor->name }}</h1><p class="mt-2 text-sm text-slate-500">Ficha maestra del medico.</p></div>@can('masters.manage')<a href="{{ route('masters.doctors.edit', $doctor) }}" class="inline-flex items-center justify-center bg-sky-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-sky-800">Editar medico</a>@endcan</div>
        @if (session('status'))<div class="border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('status') }}</div>@endif
        <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach ([['CMP', $doctor->cmp ?: 'No registrado'], ['Especialidad', str_replace('_', ' ', ucfirst($doctor->specialty ?: 'otro'))], ['Perfil comercial', ucfirst($doctor->commercial_profile ?: 'nuevo')], ['Potencial', ucfirst($doctor->potential ?: 'medio')]] as [$label, $value])<div class="border border-slate-200 bg-white p-5"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">{{ $label }}</p><p class="mt-2 font-semibold text-slate-950">{{ $value }}</p></div>@endforeach</section>
        <div class="grid gap-6 lg:grid-cols-2"><section class="border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-950">Datos generales</h2><dl class="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Institucion principal</dt><dd class="mt-1 text-slate-700">{{ $doctor->institution?->name ?: 'No registrada' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Responsable comercial</dt><dd class="mt-1 text-slate-700">{{ $doctor->commercialOwner?->name ?: 'No asignado' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Telefono</dt><dd class="mt-1 text-slate-700">{{ $doctor->phone ?: '—' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Email</dt><dd class="mt-1 text-slate-700">{{ $doctor->email ?: '—' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Estado</dt><dd class="mt-1 text-slate-700">{{ $doctor->active ? 'Activo' : 'Inactivo' }}</dd></div></dl></section><section class="border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-950">Resumen comercial</h2><p class="mt-4 text-sm text-slate-600">Consumo valorizado registrado: <strong class="text-slate-950">S/ {{ number_format($valuedConsumption, 2) }}</strong></p><p class="mt-3 text-sm text-slate-600">Oportunidades registradas: <strong class="text-slate-950">{{ $commercialOpportunities->count() }}</strong></p><p class="mt-4 whitespace-pre-line text-sm text-slate-700">{{ $doctor->observations ?: 'Sin observaciones registradas.' }}</p></section></div>
        <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">Casos recientes</h2></div>@if ($recentCases->isEmpty())<p class="px-5 py-8 text-sm text-slate-500">No hay solicitudes asociadas.</p>@else<div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Caso</th><th class="px-5 py-3">Institucion</th><th class="px-5 py-3">Cirugia</th><th class="px-5 py-3">Estado</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($recentCases as $case)<tr><td class="px-5 py-4"><a href="{{ route('cases.show', $case) }}" class="font-semibold text-sky-700">{{ $case->case_code }}</a></td><td class="px-5 py-4">{{ $case->institution?->name ?: '—' }}</td><td class="px-5 py-4">{{ $case->surgeryType?->name ?: '—' }}</td><td class="px-5 py-4">{{ $case->status->label() }}</td></tr>@endforeach</tbody></table></div>@endif</section>
    </div>
@endsection
