@extends('layouts.ops')

@section('title', 'Reporte de facturacion | OPS BIOMED MR8')

@section('content')
    <style>@media print { header, .no-print { display: none !important; } main { max-width: none !important; padding: 0 !important; } .shadow-sm { box-shadow: none !important; } }</style>
    <div class="space-y-6">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a href="{{ route('reports.index') }}" class="text-sm font-medium text-sky-700 hover:text-sky-900 no-print">Volver a reportes</a><h1 class="mt-3 text-2xl font-semibold tracking-tight text-slate-950">Reporte de facturacion y cobranza</h1><p class="mt-2 text-sm text-slate-500">Control financiero de casos del periodo seleccionado.</p></div><div class="flex flex-wrap gap-3 no-print"><a href="{{ route('reports.export', array_merge(['type' => 'billing'], request()->query())) }}" class="border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Exportar CSV</a><a href="{{ request()->fullUrlWithQuery(['print' => 1]) }}" class="bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Vista imprimible</a></div></div>
        @include('reports.partials.filters', ['action' => route('reports.billing')])
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-7">
            @foreach ([['label' => 'Monto valorizado', 'value' => 'S/ '.number_format($report['metrics']['valued_amount'], 2)], ['label' => 'Monto facturado', 'value' => 'S/ '.number_format($report['metrics']['invoiced_amount'], 2)], ['label' => 'Monto pendiente', 'value' => 'S/ '.number_format($report['metrics']['pending_amount'], 2)], ['label' => 'Monto vencido', 'value' => 'S/ '.number_format($report['metrics']['overdue_amount'], 2)], ['label' => 'Pendientes de OC', 'value' => $report['metrics']['pending_purchase_order']], ['label' => 'Pendientes de factura', 'value' => $report['metrics']['pending_invoice']], ['label' => 'Costo cero pendiente', 'value' => $report['metrics']['zero_cost_pending']]] as $metric)<article class="border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">{{ $metric['label'] }}</p><p class="mt-3 text-2xl font-semibold text-slate-950">{{ $metric['value'] }}</p></article>@endforeach
        </section>
        <section class="grid gap-6 lg:grid-cols-2">
            <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">Deuda por institucion</h2></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3 font-semibold">Institucion</th><th class="px-5 py-3 font-semibold">Casos</th><th class="px-5 py-3 font-semibold">Pendiente</th><th class="px-5 py-3 font-semibold">Vencido</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($report['by_institution'] as $row)<tr><td class="px-5 py-3 text-slate-700">{{ $row['label'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['cases'] }}</td><td class="px-5 py-3 font-semibold text-slate-900">S/ {{ number_format($row['pending'], 2) }}</td><td class="px-5 py-3 font-semibold text-rose-700">S/ {{ number_format($row['overdue'], 2) }}</td></tr>@empty<tr><td colspan="4" class="px-5 py-5 text-sm text-slate-500">Sin deuda en el periodo.</td></tr>@endforelse</tbody></table></div></section>
            <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">Deuda por antiguedad</h2></div><div class="divide-y divide-slate-100">@foreach ($report['aging'] as $label => $row)<div class="flex items-center justify-between px-5 py-3 text-sm"><span class="text-slate-700">{{ $label }}</span><span class="font-semibold text-slate-900">{{ $row['cases'] }} casos · S/ {{ number_format($row['amount'], 2) }}</span></div>@endforeach</div></section>
        </section>
        <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">Costo cero y estado administrativo</h2><p class="mt-1 text-sm text-slate-500">Aprobado no se considera deuda; pendiente sigue siendo tarea administrativa.</p></div><div class="grid gap-4 p-5 sm:grid-cols-3"><div class="border border-amber-200 bg-amber-50 p-4"><p class="text-sm text-amber-700">Pendientes</p><p class="mt-2 text-2xl font-semibold text-amber-900">{{ $report['metrics']['zero_cost_pending'] }}</p></div><div class="border border-emerald-200 bg-emerald-50 p-4"><p class="text-sm text-emerald-700">Aprobados</p><p class="mt-2 text-2xl font-semibold text-emerald-900">{{ $report['metrics']['zero_cost_approved'] }}</p></div><div class="border border-rose-200 bg-rose-50 p-4"><p class="text-sm text-rose-700">Rechazados</p><p class="mt-2 text-2xl font-semibold text-rose-900">{{ $report['metrics']['zero_cost_rejected'] }}</p></div></div></section>
        <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">Casos facturables</h2></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3 font-semibold">Caso</th><th class="px-5 py-3 font-semibold">Institucion</th><th class="px-5 py-3 font-semibold">Estado</th><th class="px-5 py-3 font-semibold">Total</th><th class="px-5 py-3 font-semibold">Saldo</th><th class="px-5 py-3 font-semibold">Pago</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($report['records'] as $row)<tr><td class="px-5 py-3 text-sky-700">{{ $row['case_code'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['institution'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['invoice_status'] }}</td><td class="px-5 py-3 text-slate-900">S/ {{ number_format($row['amount'], 2) }}</td><td class="px-5 py-3 font-semibold text-rose-700">S/ {{ number_format($row['balance'], 2) }}</td><td class="px-5 py-3 text-slate-700">{{ $row['payment_status'] }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-5 text-sm text-slate-500">Sin registros para el periodo.</td></tr>@endforelse</tbody></table></div></section>
    </div>
@endsection
