@extends('layouts.ops')

@section('title', 'Reporte comercial | OPS BIOMED MR8')

@section('content')
    <style>@media print { header, .no-print { display: none !important; } main { max-width: none !important; padding: 0 !important; } .shadow-sm { box-shadow: none !important; } }</style>
    <div class="space-y-6">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a href="{{ route('reports.index') }}" class="text-sm font-medium text-sky-700 hover:text-sky-900 no-print">Volver a reportes</a><h1 class="mt-3 text-2xl font-semibold tracking-tight text-slate-950">Reporte comercial</h1><p class="mt-2 text-sm text-slate-500">Consumo y comportamiento de cuentas en el periodo seleccionado.</p></div><div class="flex flex-wrap gap-3 no-print"><a href="{{ route('reports.export', array_merge(['type' => 'commercial'], request()->query())) }}" class="border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Exportar CSV</a><a href="{{ request()->fullUrlWithQuery(['print' => 1]) }}" class="bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Vista imprimible</a></div></div>
        @include('reports.partials.filters', ['action' => route('reports.commercial')])
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
            @foreach ([['label' => 'Unidades consumidas', 'value' => $report['metrics']['consumption_units']], ['label' => 'Consumo valorizado', 'value' => 'S/ '.number_format($report['metrics']['consumption_value'], 2)], ['label' => 'Instituciones con consumo', 'value' => $report['metrics']['institutions_with_consumption']], ['label' => 'Medicos clave', 'value' => $report['metrics']['key_doctors']], ['label' => 'Casos costo cero', 'value' => $report['metrics']['zero_cost_cases']]] as $metric)<article class="border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">{{ $metric['label'] }}</p><p class="mt-3 text-2xl font-semibold text-slate-950">{{ $metric['value'] }}</p></article>@endforeach
        </section>
        <section class="grid gap-6 lg:grid-cols-2">
            @foreach ([['title' => 'Consumo por institucion / cuenta', 'rows' => $report['by_institution']], ['title' => 'Consumo por medico', 'rows' => $report['by_doctor']], ['title' => 'Productos mas usados', 'rows' => $report['by_product']], ['title' => 'Instituciones con mayor crecimiento', 'rows' => $report['growth']], ['title' => 'Oportunidades de cesion de uso', 'rows' => $report['opportunities']]] as $group)
                <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">{{ $group['title'] }}</h2></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3 font-semibold">Dimension</th><th class="px-5 py-3 font-semibold">Unidades</th><th class="px-5 py-3 font-semibold">Casos</th>@if ($group['title'] === 'Instituciones con mayor crecimiento')<th class="px-5 py-3 font-semibold">Crecimiento</th>@endif</tr></thead><tbody class="divide-y divide-slate-100">@forelse ($group['rows'] as $row)<tr><td class="px-5 py-3 text-slate-700">{{ $row['label'] }}@if (isset($row['reason']))<span class="mt-1 block text-xs text-slate-500">{{ $row['reason'] }}</span>@endif</td><td class="px-5 py-3 font-semibold text-slate-900">{{ $row['units'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['cases'] }}</td>@if ($group['title'] === 'Instituciones con mayor crecimiento')<td class="px-5 py-3 font-semibold {{ $row['growth_percent'] >= 0 ? 'text-emerald-700' : 'text-rose-700' }}">{{ $row['growth_percent'] }}%</td>@endif</tr>@empty<tr><td colspan="4" class="px-5 py-5 text-sm text-slate-500">Sin datos para el periodo.</td></tr>@endforelse</tbody></table></div></section>
            @endforeach
            <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">Cuentas sin consumo reciente</h2></div><div class="divide-y divide-slate-100">@forelse ($report['no_recent_consumption'] as $institution)<p class="px-5 py-3 text-sm text-slate-700">{{ $institution->name }}</p>@empty<p class="px-5 py-5 text-sm text-slate-500">Todas las instituciones tuvieron consumo.</p>@endforelse</div></section>
            <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">Casos costo cero por cuenta</h2></div><div class="divide-y divide-slate-100">@forelse ($report['zero_cost_by_institution'] as $row)<div class="flex items-center justify-between px-5 py-3 text-sm"><span class="text-slate-700">{{ $row['label'] }}</span><span class="font-semibold text-amber-700">{{ $row['cases'] }} casos / {{ $row['units'] }} unidades</span></div>@empty<p class="px-5 py-5 text-sm text-slate-500">Sin costo cero para el periodo.</p>@endforelse</div></section>
        </section>
    </div>
@endsection
