@extends('layouts.ops')

@section('title', 'Reporte de inventario | OPS BIOMED MR8')

@section('content')
    <style>@media print { header, .no-print { display: none !important; } main { max-width: none !important; padding: 0 !important; } .shadow-sm { box-shadow: none !important; } }</style>
    <div class="space-y-6">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a href="{{ route('reports.index') }}" class="text-sm font-medium text-sky-700 hover:text-sky-900 no-print">Volver a reportes</a><h1 class="mt-3 text-2xl font-semibold tracking-tight text-slate-950">Reporte de inventario</h1><p class="mt-2 text-sm text-slate-500">Cobertura, alertas y reposicion MR8.</p></div><div class="flex flex-wrap gap-3 no-print"><a href="{{ route('reports.export', array_merge(['type' => 'inventory'], request()->query())) }}" class="border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Exportar CSV</a><a href="{{ request()->fullUrlWithQuery(['print' => 1]) }}" class="bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Vista imprimible</a></div></div>
        @include('reports.partials.filters', ['action' => route('reports.inventory')])
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
            @foreach ([['label' => 'Bajo minimo', 'value' => $report['metrics']['under_minimum']], ['label' => 'Bajo objetivo', 'value' => $report['metrics']['under_target']], ['label' => 'Criticos en riesgo', 'value' => $report['metrics']['critical_combinations']], ['label' => 'Vencidos', 'value' => $report['metrics']['expired']], ['label' => 'Bloqueados / cuarentena', 'value' => $report['metrics']['blocked'] + $report['metrics']['quarantine']], ['label' => 'Inconsistencias', 'value' => $report['metrics']['pending_inconsistencies']]] as $metric)<article class="border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">{{ $metric['label'] }}</p><p class="mt-3 text-2xl font-semibold text-slate-950">{{ $metric['value'] }}</p></article>@endforeach
        </section>
        <section class="grid gap-6 lg:grid-cols-2">
            @foreach ([['title' => 'Productos criticos bajo minimo', 'rows' => $report['under_minimum']], ['title' => 'Productos bajo objetivo', 'rows' => $report['under_target']]] as $group)
                <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">{{ $group['title'] }}</h2></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3 font-semibold">Cirugia</th><th class="px-5 py-3 font-semibold">Combinacion</th><th class="px-5 py-3 font-semibold">Neto</th><th class="px-5 py-3 font-semibold">Min / obj</th><th class="px-5 py-3 font-semibold">Semaforo</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($group['rows'] as $row)<tr><td class="px-5 py-3 text-slate-700">{{ $row['surgery_type'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['label'] }}</td><td class="px-5 py-3 font-semibold text-slate-900">{{ $row['available_net'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['minimum'] }} / {{ $row['target'] }}</td><td class="px-5 py-3 font-semibold {{ $row['risk'] === 'red' ? 'text-rose-700' : 'text-amber-700' }}">{{ $row['risk_label'] }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-5 text-sm text-slate-500">Sin combinaciones para el filtro.</td></tr>@endforelse</tbody></table></div></section>
            @endforeach
        </section>
        <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">Forecast de compra por prioridad</h2></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3 font-semibold">Urgencia</th><th class="px-5 py-3 font-semibold">Cirugia</th><th class="px-5 py-3 font-semibold">Producto</th><th class="px-5 py-3 font-semibold">Neto inmediato</th><th class="px-5 py-3 font-semibold">YSAN respaldo</th><th class="px-5 py-3 font-semibold">Compra sugerida</th><th class="px-5 py-3 font-semibold">Accion</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($report['forecast'] as $row)<tr><td class="px-5 py-3 font-semibold {{ $row['urgency'] === 'critical' ? 'text-rose-700' : ($row['urgency'] === 'high' ? 'text-amber-700' : 'text-emerald-700') }}">{{ $row['urgency_label'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['surgery_type'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['product_code'] }}</td><td class="px-5 py-3 text-slate-900">{{ $row['stock_immediate_net'] }}</td><td class="px-5 py-3 text-slate-700">{{ $row['stock_ysan'] }}</td><td class="px-5 py-3 font-semibold text-slate-900">{{ $row['suggested_purchase'] }}</td><td class="max-w-sm px-5 py-3 text-xs text-slate-600">{{ $row['action'] }}</td></tr>@empty<tr><td colspan="7" class="px-5 py-5 text-sm text-slate-500">Sin forecast para el filtro.</td></tr>@endforelse</tbody></table></div></section>
        <section class="grid gap-6 lg:grid-cols-2">
            @foreach ([['title' => 'Productos vencidos', 'rows' => $report['expired_lots']], ['title' => 'Proximos a vencer', 'rows' => $report['expiring_lots']], ['title' => 'Productos bloqueados', 'rows' => $report['blocked_lots']], ['title' => 'Productos en cuarentena', 'rows' => $report['quarantine_lots']]] as $group)
                <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold text-slate-950">{{ $group['title'] }}</h2></div><div class="divide-y divide-slate-100">@forelse ($group['rows'] as $lot)<div class="px-5 py-3 text-sm"><p class="font-semibold text-slate-800">{{ $lot->product?->product_code }} · {{ $lot->product?->name }}</p><p class="mt-1 text-xs text-slate-500">Lote {{ $lot->lot ?: 'Sin lote' }} · {{ $lot->warehouse?->name }} · Cantidad {{ $lot->quantity }}</p></div>@empty<p class="px-5 py-5 text-sm text-slate-500">Sin lotes en esta categoria.</p>@endforelse</div></section>
            @endforeach
        </section>
        <section class="border border-orange-200 bg-orange-50 shadow-sm"><div class="border-b border-orange-200 px-5 py-4"><h2 class="font-semibold text-orange-900">Inconsistencias pendientes</h2></div><div class="divide-y divide-orange-100">@forelse ($report['issues'] as $issue)<div class="px-5 py-3 text-sm"><p class="font-semibold text-orange-900">{{ $issue->product?->product_code ?? $issue->product_code }} · {{ $issue->warehouse?->name ?? $issue->warehouse_name }}</p><p class="mt-1 text-orange-800">Cantidad {{ $issue->quantity }} · {{ $issue->message }}</p></div>@empty<p class="px-5 py-5 text-sm text-orange-800">No hay inconsistencias pendientes.</p>@endforelse</div></section>
        <section class="border border-slate-200 bg-white shadow-sm">
            <div class="flex flex-col justify-between gap-2 border-b border-slate-200 px-5 py-4 sm:flex-row sm:items-center"><div><h2 class="font-semibold text-slate-950">Fallas de inventario</h2><p class="mt-1 text-sm text-slate-500">Productos afectados y tiempo promedio de liberacion tecnica.</p></div><span class="text-sm font-semibold text-slate-700">Promedio: {{ $report['failure_report']['metrics']['average_release_hours'] }} h</span></div>
            <div class="grid gap-6 p-5 lg:grid-cols-3">
                <div><h3 class="text-sm font-semibold text-slate-900">Por mes</h3><div class="mt-3 divide-y divide-slate-100">@forelse ($report['failure_report']['by_month'] as $row)<div class="flex justify-between gap-3 py-2 text-sm"><span>{{ $row['label'] }}</span><span class="font-semibold">{{ $row['failures'] }}</span></div>@empty<p class="py-2 text-sm text-slate-500">Sin fallas.</p>@endforelse</div></div>
                <div><h3 class="text-sm font-semibold text-slate-900">Por producto</h3><div class="mt-3 divide-y divide-slate-100">@forelse ($report['failure_report']['by_product']->take(10) as $row)<div class="flex justify-between gap-3 py-2 text-sm"><span>{{ $row['label'] }}</span><span class="font-semibold text-rose-700">{{ $row['failures'] }}</span></div>@empty<p class="py-2 text-sm text-slate-500">Sin fallas.</p>@endforelse</div></div>
                <div><h3 class="text-sm font-semibold text-slate-900">Fallas repetidas</h3><div class="mt-3 divide-y divide-slate-100">@forelse ($report['failure_report']['repeated_products'] as $row)<div class="flex justify-between gap-3 py-2 text-sm"><span>{{ $row['label'] }}</span><span class="font-semibold text-rose-700">{{ $row['failures'] }}</span></div>@empty<p class="py-2 text-sm text-slate-500">No hay productos repetidos.</p>@endforelse</div></div>
            </div>
        </section>
    </div>
@endsection
