@extends('layouts.ops')

@section('title', 'Precios de productos | OPS BIOMED MR8')

@section('content')
    <div class="space-y-6">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-sky-700">Maestros operativos</p><h1 class="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Precios de productos</h1><p class="mt-2 text-sm text-slate-500">Historial de precios vigentes y vencidos para valorizacion MR8.</p></div>@can('prices.manage')<a href="{{ route('masters.prices.create') }}" class="inline-flex items-center justify-center bg-sky-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-sky-800">Nuevo precio</a>@endcan</div>
        <form method="GET" class="grid gap-4 border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><div class="lg:col-span-2"><label for="product_id" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Producto</label><select id="product_id" name="product_id" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todos</option>@foreach ($products as $product)<option value="{{ $product->id }}" @selected(request('product_id') == $product->id)>{{ $product->product_code }} - {{ $product->name }}</option>@endforeach</select></div><div><label for="institution_id" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Institucion</label><select id="institution_id" name="institution_id" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todas</option>@foreach ($institutions as $institution)<option value="{{ $institution->id }}" @selected(request('institution_id') == $institution->id)>{{ $institution->name }}</option>@endforeach</select></div><div><label for="doctor_id" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Medico</label><select id="doctor_id" name="doctor_id" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todos</option>@foreach ($doctors as $doctor)<option value="{{ $doctor->id }}" @selected(request('doctor_id') == $doctor->id)>{{ $doctor->name }}</option>@endforeach</select></div><div><label for="active" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Estado</label><select id="active" name="active" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todos</option><option value="active" @selected(request('active') === 'active')>Activos</option><option value="inactive" @selected(request('active') === 'inactive')>Inactivos</option></select></div><div><label for="price_type" class="block text-xs font-semibold uppercase tracking-wide text-slate-500">Tipo</label><select id="price_type" name="price_type" class="mt-1.5 block w-full border-slate-300 bg-white text-sm"><option value="">Todos</option>@foreach ($priceTypes as $value)<option value="{{ $value }}" @selected(request('price_type') === $value)>{{ str_replace('_', ' ', ucfirst($value)) }}</option>@endforeach</select></div><div class="sm:col-span-2 lg:col-span-5 flex justify-end gap-3"><a href="{{ route('masters.prices.index') }}" class="border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Limpiar</a><button type="submit" class="bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800">Filtrar</button></div></form>
        <div class="overflow-hidden border border-slate-200 bg-white shadow-sm">@if ($prices->isEmpty())<div class="px-6 py-12 text-center text-sm text-slate-500">No hay precios registrados.</div>@else<div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Producto</th><th class="px-5 py-3">Alcance</th><th class="px-5 py-3">Tipo</th><th class="px-5 py-3">Precio / minimo</th><th class="px-5 py-3">Vigencia</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($prices as $price)<tr class="align-top"><td class="px-5 py-4"><p class="font-semibold text-slate-950">{{ $price->product?->product_code }}</p><p class="mt-1 max-w-xs text-slate-600">{{ $price->product?->name }}</p></td><td class="px-5 py-4 text-slate-600">{{ $price->doctor?->name ?: ($price->institution?->name ?: 'General') }}@if ($price->doctor && $price->institution)<p class="mt-1 text-xs text-slate-500">{{ $price->institution->name }}</p>@endif</td><td class="px-5 py-4 text-slate-600">{{ str_replace('_', ' ', ucfirst($price->price_type ?: 'lista')) }}</td><td class="px-5 py-4 whitespace-nowrap text-slate-700"><strong>{{ number_format((float) $price->unit_price, 2) }} {{ $price->currency }}</strong><p class="mt-1 text-xs text-slate-500">Min: {{ $price->minimum_price !== null ? number_format((float) $price->minimum_price, 2).' '.$price->currency : '—' }}</p></td><td class="px-5 py-4 whitespace-nowrap text-slate-600">{{ $price->valid_from?->format('d/m/Y') ?: '—' }}<span class="text-slate-400"> a </span>{{ $price->valid_until?->format('d/m/Y') ?: 'abierta' }}</td><td class="px-5 py-4"><span class="inline-flex px-2 py-1 text-xs font-semibold {{ $price->active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $price->active ? 'Activo' : 'Inactivo' }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('masters.prices.edit', $price) }}" class="font-semibold text-slate-700 hover:text-sky-700">Editar</a></td></tr>@endforeach</tbody></table></div><div class="border-t border-slate-200 px-5 py-4">{{ $prices->links() }}</div>@endif</div>
    </div>
@endsection
